### ISSUE TITLE
Managing Android keystores

### ISSUE THREAD

**Issue by ininmm** [Ptt-official-app/Ptt-Android#14]
In GitLab by @in_in_mm on Nov 11, 2020, 13:59

根據之前會議中 iOS 同仁的建議，Android 這邊應該也需要實作一個管理 keystore 的機制以利後續 open source 後的 CI/CD 開發及 App 上架。

預計要管理的 Keystore 會有兩個：
1. debug keystore for CI/CD and collaborating on GitHub
2. release keystore for setting app up to google play

 open source 後需要盡可能地把個人訊息或是比較敏感的訊息去掉。

**Comment by ininmm** [comment]
In GitLab by @in_in_mm on Nov 14, 2020, 00:07

changed title from **{-專案 keystore 管理-}** to **{+Managing Android keystores+}**

**Comment by PichuChen** [comment]
經驗上 release keystore 可由專案某人保管好，密碼不要設太複雜即可，因為還有一層上架的 Google Play 在擋，實務上常常因為忘了交接導致 release keystore消失。
