### ISSUE TITLE
Implement MVVM - ArticleReadFragment

### ISSUE THREAD

**Issue by ininmm** [Ptt-official-app/Ptt-Android#18]
In GitLab by @aidan79225 on Nov 19, 2020, 22:34

**Comment by ininmm** [comment]
In GitLab by @aidan79225 on Nov 19, 2020, 22:35

marked this issue as related to #1

**Comment by kenhuang1120** [comment]
Finished in https://github.com/Ptt-official-app/Ptt-Android/pull/76
